name: Publish package

on:
  push:
    tags:
      - "v*"

env:
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}
  NUGET_SOURCE_URL: "https://api.nuget.org/v3/index.json"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Pack
        run: dotnet pack **/Funcer.csproj --no-restore --no-build --configuration Release --include-symbols --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }} /p:SymbolPackageFormat=snupkg
      - name: Push to NuGet
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/Funcer*.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }}
